# Generated by Django 2.0.7 on 2019-01-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='average_vote',
        ),
        migrations.AddField(
            model_name='person',
            name='people_voted',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='total_vote',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
