# Generated by Django 2.0.7 on 2019-01-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190112_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='average_vote',
            field=models.IntegerField(default='0'),
        ),
    ]
