# Generated by Django 2.0.7 on 2019-01-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_person_average_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='average_vote',
            field=models.IntegerField(),
        ),
    ]
