# Generated by Django 2.0.7 on 2019-01-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190112_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='average_vote',
            field=models.IntegerField(default='0'),
        ),
    ]
